# Generated by Django 6.0.7 on 2026-07-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_desc',
            new_name='recipe_desc',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
    ]
