# Generated by Django 6.0.7 on 2026-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('student', 'date_of_report_card_generation'), name='unique_student_reportcard'),
        ),
    ]
