# Generated by Django 6.0.7 on 2026-07-29 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_alter_reportcard_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2026, 7, 29, 15, 38, 1, 911789, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
